name: nextfitx
description: nextfitX - Your Personal Fitness Companion
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_carousel_widget: ^3.1.0
  fl_chart: ^1.0.0
#  simple_animation_progress_bar: ^1.6.0
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.8.5
  readmore: ^3.0.0
  percent_indicator: ^4.2.3
  calendar_agenda:
    path: dev_lib/calendar_agenda/
  intl: ^0.18.1
  provider: ^6.1.1
  scrollable_positioned_list: ^0.3.8
  
  # Firebase dependencies
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  google_sign_in: ^6.1.6
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  uuid: ^4.2.2
  path: ^1.8.3
  image_picker: ^1.0.7
  url_launcher: ^6.3.1
  youtube_player_flutter: ^9.0.3
  image: ^4.1.7
  photo_view: ^0.15.0
  flutter_image_compress: ^2.4.0

  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  conditional_builder_null_safety: ^0.0.6
  smooth_page_indicator: ^1.1.0
  flutter_styled_toast: ^2.2.1
  skeletonizer: ^1.3.0
  flutter_blue_plus: ^1.31.17
  shimmer: ^2.0.0
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  flutter_svg: ^2.0.10+1

dependency_overrides: 
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logofix.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/logofix.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img/logofix.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/logofix.png"
