// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr0nbYbBCIF5dqDLY6DSDIrM_YdRf-dNo',
    appId: '1:407416287783:web:78ff70fe501b07cb411402',
    messagingSenderId: '407416287783',
    projectId: 'fitness-7292e',
    authDomain: 'fitness-7292e.firebaseapp.com',
    storageBucket: 'fitness-7292e.firebasestorage.app',
    measurementId: 'G-FVKXT88CW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8YkDm7eCQNcKFBA3gQ1cF17iKIP4Wieg',
    appId: '1:407416287783:android:c4bfa996403160d6411402',
    messagingSenderId: '407416287783',
    projectId: 'fitness-7292e',
    storageBucket: 'fitness-7292e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuvBU4c_ol60aDX4BUdVj0KDwsO8YtfUk',
    appId: '1:407416287783:ios:ba0b1c379f68f2df411402',
    messagingSenderId: '407416287783',
    projectId: 'fitness-7292e',
    storageBucket: 'fitness-7292e.firebasestorage.app',
    androidClientId:
        '407416287783-hb39beo7st5251ojfisc4ph8022cqino.apps.googleusercontent.com',
    iosClientId:
        '407416287783-oknnk7rden86efpcitnb995qs7gfrcfo.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuvBU4c_ol60aDX4BUdVj0KDwsO8YtfUk',
    appId: '1:407416287783:ios:ba0b1c379f68f2df411402',
    messagingSenderId: '407416287783',
    projectId: 'fitness-7292e',
    storageBucket: 'fitness-7292e.firebasestorage.app',
    androidClientId:
        '407416287783-hb39beo7st5251ojfisc4ph8022cqino.apps.googleusercontent.com',
    iosClientId:
        '407416287783-oknnk7rden86efpcitnb995qs7gfrcfo.apps.googleusercontent.com',
    iosBundleId: 'com.codeforany.fitness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr0nbYbBCIF5dqDLY6DSDIrM_YdRf-dNo',
    appId: '1:407416287783:web:4aa9ecca4631fe85411402',
    messagingSenderId: '407416287783',
    projectId: 'fitness-7292e',
    authDomain: 'fitness-7292e.firebaseapp.com',
    storageBucket: 'fitness-7292e.firebasestorage.app',
    measurementId: 'G-B2L8Z812DQ',
  );
}
